export const columns = [
  'Name',
  'Status',
  'OS',
  'Tags',
  'Data Collector',
  'RHC Status',
  'System Update Method',
  'Last seen',
];

export const rows = [
  {
    name: 'rhiqe.qqapqzkpfd',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.0',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 minute ago',
    group: 'N/A',
  },
  {
    name: 'sathyper-a57f0130-a4d7-4b44-9efb-6637273fffaf',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.1',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '10 minutes ago',
    group: 'Production',
  },
  {
    name: 'satcloud-aws-9ef115b8-42a9-4990-9bff-06c767b11b7e',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.2',
    tags: { location: 'North America', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'gfdhszvy.test',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.3',
    tags: { location: 'North America', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'rem_029bfa99-3b8f-47b2-ae9d-50502480a08b',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.4',
    tags: { location: 'North America', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Security',
  },
  {
    name: 'rem_68886cf8-21fb-411d-83a3-3f1a6e0e454b',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.0',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Production',
  },
  {
    name: 'rhiqe.nwkgfpxzqe',
    status: 'Fresh',
    operatingSystem: 'RHEL 9.1',
    tags: { location: 'South America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Production',
  },
  {
    name: 'rhiqe.blyrcltxsy',
    status: 'Stale',
    operatingSystem: 'RHEL 9.2',
    tags: { location: 'South America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Production',
  },
  {
    name: 'rem_9bba64da-4cb3-4256-9119-fd93b21a26bc',
    status: 'Stale',
    operatingSystem: 'RHEL 9.3',
    tags: { location: 'Europe', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'peahpubb',
    status: 'Stale',
    operatingSystem: 'RHEL 9.4',
    tags: { location: 'North America', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'tlweutnn',
    status: 'Stale',
    operatingSystem: 'RHEL 9.0',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Production',
  },
  {
    name: 'rem_3b74d99e-d113-4d95-a6df-f301a44d1045',
    status: 'Stale',
    operatingSystem: 'RHEL 9.0',
    tags: { location: 'Europe', environment: 'Staging' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'iqe-patch-rhel-80',
    status: 'Stale',
    operatingSystem: 'RHEL 9.1',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'insights-client',
    rhcStatus: 'Active',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Production',
  },
  {
    name: 'rhiqe.msqxzliano',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.7',
    tags: { location: 'Europe', environment: 'Staging' },
    dataCollector: 'subscription-manager',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Staging',
  },
  {
    name: 'rhiqe.lgbnjhdwhg',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.8',
    tags: { location: 'Europe', environment: 'Staging' },
    dataCollector: 'subscription-manager',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'yum',
    lastSeen: '1 hour ago',
    group: 'Security ',
  },
  {
    name: 'csbprodrhel93-897',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.9',
    tags: { location: 'Asia', environment: 'Preview' },
    dataCollector: 'subscription-manager',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'dnf',
    lastSeen: '1 month ago',
    group: 'Preview',
  },
  {
    name: 'LKQohNnl',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.8',
    tags: { location: 'North America', environment: 'Staging' },
    dataCollector: 'subscription-manager',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'dnf',
    lastSeen: '1 month ago',
    group: 'Staging',
  },
  {
    name: 'FCHtHHZd',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.9',
    tags: { location: 'North America', environment: 'Production' },
    dataCollector: 'Satellite/Discovery',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'dnf',
    lastSeen: '1 month ago',
    group: 'Production',
  },
  {
    name: 'csbprodrhel92-896',
    status: 'Stale warning',
    operatingSystem: 'RHEL 8.9',
    tags: { location: 'Asia', environment: 'Preview' },
    dataCollector: 'insights-client not connected',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'dnf',
    lastSeen: '1 month ago',
    group: 'Preview',
  },
  {
    name: 'YknnoxQk',
    status: 'Unknown',
    operatingSystem: 'RHEL 8.9',
    tags: { location: 'Asia', environment: 'Preview' },
    dataCollector: 'insights-client not connected',
    rhcStatus: 'Inactive',
    systemUpdateMethod: 'rpm-ostree',
    lastSeen: '1 year ago',
    group: 'Preview',
  },
];
